language: node_js
dist: trusty
sudo: required
node_js: '8'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install
- bower install
- chmod -R +x ./bower_components/git-version-tagging
script:
- xvfb-run npm test
